version: '3.5'
services:
  web:
    build:
      context: .
    ports:
      - 3000:3000
    volumes: &volumes
      - .:/app:cached
      - ~/.bash_history:/root/.bash_history
      - bundle_cache:/usr/local/bundle
    command: bin/rails s -b '0.0.0.0' -p 3000
    depends_on:
      - postgres
      #- sidekiq
    env_file: envvars
    environment: &environment
      RAILS_LOG_TO_STDOUT: 'true'
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 'frontend'

  frontend:
    image: one_vs_100_web
    volumes: *volumes
    command: bin/webpack-dev-server
    ports:
      - 3035:3035
    env_file: envvars
    environment:
      <<: *environment
      WEBPACK_DEFAULT_LISTEN_HOST_ADDR: '0.0.0.0'

  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: one_vs_100_test
      POSTGRES_USER: one_vs_100
      POSTGRES_PASSWORD: one_vs_100

  # sidekiq:
  #   image: one_vs_100_web
  #   depends_on:
  #     - postgres
  #   volumes: *volumes
  #   env_file: envvars
  #   environment:
  #     <<: *environment
  #   command: sidekiq

volumes:
  bundle_cache:
